from sqlalchemy import select, table, literal_column, text, desc, asc
from sqlalchemy.dialects import postgresql
from state import PlatformState

def sql_generator_agent(state: PlatformState) -> dict:
    """
    Deterministically compiles a PostgreSQL query using SQLAlchemy Core
    based entirely on the Planner's JSON blueprint. No LLM used.
    """
    print("\n==================================================")
    print(" [SQL GENERATOR NODE] Compiling SQLAlchemy Query...")
    print("==================================================")

    # Extract the blueprint generated by the Planner
    plan_state = state.get("plan", {})
    blueprint = plan_state.get("blueprint", {})

    if not blueprint:
        print("❌ [SQL GENERATOR NODE] Error: No blueprint found in state.")
        return {"sql_query": "", "execution_status": "failed", "error_message": "Missing blueprint."}

    try:
        # 1. Base Tables
        table_names = blueprint.get("tables", [])
        if not table_names:
            raise ValueError("Blueprint must specify at least one table.")
            
        tables = [table(t) for t in table_names]

        # 2. Select Columns & Aggregations
        select_items = []
        for metric in blueprint.get("metrics", []):
            select_items.append(literal_column(metric))
            
        for agg in blueprint.get("aggregations", []):
            select_items.append(literal_column(agg))

        # Default to SELECT * if planner forgot metrics
        if not select_items:
            select_items.append(literal_column("*"))

        # Initialize the SQLAlchemy Select object
        query = select(*select_items)

        # 3. Add FROM clauses (Implicit cross-joins, resolved by WHERE conditions)
        for t in tables:
            query = query.select_from(t)

        # 4. WHERE Clauses (Filters & Implicit Joins)
        filters = blueprint.get("filters", [])
        for f in filters:
            column_name = f.get("column")
            operator = f.get("operator", "=").upper()
            value = f.get("value")
            
            # Constructing the WHERE clause using raw text to support complex operators (ILIKE, IN, etc.)
            condition = text(f"{column_name} {operator} {value}")
            query = query.where(condition)

        # 5. GROUP BY
        group_by_cols = blueprint.get("group_by", [])
        if group_by_cols:
            query = query.group_by(*[literal_column(gb) for gb in group_by_cols])

        # 6. ORDER BY
        sort_by = blueprint.get("sort_by")
        if sort_by:
            # Simple parsing: "total_revenue DESC" -> column: "total_revenue", direction: "DESC"
            parts = sort_by.strip().split(" ")
            sort_col = parts[0]
            if len(parts) > 1 and parts[1].upper() == "DESC":
                query = query.order_by(desc(literal_column(sort_col)))
            else:
                query = query.order_by(asc(literal_column(sort_col)))

        # 7. LIMIT
        limit_val = blueprint.get("limit")
        if limit_val:
            query = query.limit(int(limit_val))

        # 8. Compile to PostgreSQL Dialect
        # literal_binds=True ensures variables are injected directly into the string for the Validator to read
        compiled_sql = str(query.compile(
            dialect=postgresql.dialect(), 
            compile_kwargs={"literal_binds": True}
        ))

        print(f"✅ [SQL GENERATOR NODE] Compiled Query:\n{compiled_sql}")
        print("--------------------------------------------------")

        # Output exactly to the state variable requested
        return {
            "sql_query": compiled_sql,
            "sql_validation": {"is_valid": True, "issues": None} # Reset validation state on fresh generation
        }

    except Exception as e:
        print(f"❌ [SQL GENERATOR NODE] Compilation Failed: {str(e)}")
        print("--------------------------------------------------")
        
        return {
            "sql_query": "",
            "sql_validation": {"is_valid": False, "issues": f"SQLAlchemy Compilation Error: {str(e)}"}
        }